"""add_evidences_initial_evidence_to_patients

Revision ID: 912b8e70c52b
Revises: d77be839072d
Create Date: 2026-07-29 00:28:57.733903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912b8e70c52b'
down_revision: Union[str, Sequence[str], None] = 'd77be839072d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('evidences', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('initial_evidence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'initial_evidence')
    op.drop_column('patients', 'evidences')
    # ### end Alembic commands ###
